### ISSUE TITLE
ros2 humble on Raspberry Pi 4

### ISSUE THREAD

**Issue by Narek-939** [Schnilz/mpu9250#1]
I have installed ubuntu 22.04 and ros2 humble on Raspberry Pi 4, and I want to get IMU data but I encountered to this error

 [INFO] [launch]: All log files can be found below /home/vis/.ros/log/2023-07-27-18-38-27-728902-vis-desktop-10483
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [mpu9250-1]: process started with pid [10485]
[mpu9250-1] Traceback (most recent call last):
[mpu9250-1]   File "/home/vis/Desktop/mpu9250/install/mpu9250/lib/mpu9250/mpu9250", line 33, in <module>
[mpu9250-1]     sys.exit(load_entry_point('mpu9250', 'console_scripts', 'mpu9250')())
[mpu9250-1]   File "/home/vis/Desktop/mpu9250/build/mpu9250/mpu9250/mpu9250.py", line 114, in main
[mpu9250-1]     node = MyPythonNode()
[mpu9250-1]   File "/home/vis/Desktop/mpu9250/build/mpu9250/mpu9250/mpu9250.py", line 43, in __init__
[mpu9250-1]     bus = smbus.SMBus(self.get_parameter('i2c_port')._value)
[mpu9250-1] PermissionError: [Errno 13] Permission denied
[ERROR] [mpu9250-1]: process has died [pid 10485, exit code 1, cmd '/home/vis/Desktop/mpu9250/install/mpu9250/lib/mpu9250/mpu9250 --ros-args -r __node:=mpu9250 --params-file /tmp/launch_params_z_fxljjc'].

**Comment by schnili** [comment]
Like the error suggest, this looks like a permission error. Is your user in the i2c group? 
With some quick googling i found https://roboticsbackend.com/raspberry-pi-hardware-permissions/
